name: catcher_2
description: Plugin for error catching which provides multiple handlers for dealing with errors when they are not caught by the developer.
version: 1.0.1
homepage: https://github.com/ThexXTURBOXx/catcher_2
repository: https://github.com/ThexXTURBOXx/catcher_2
issue_tracker: https://github.com/ThexXTURBOXx/catcher_2/issues
funding:
  - https://github.com/sponsors/ThexXTURBOXx
screenshots:
  - description: "The catcher_2 logo"
    path: screenshots/logo.png
  - description: "catcher_2 in action with notifications"
    path: screenshots/1.png
  - description: "catcher_2 in action with emails"
    path: screenshots/3.png
  - description: "catcher_2 in action with dialogs"
    path: screenshots/6.png
topics:
  - analysis
  - errors
  - flutter
  - logging

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^11.5.0
  device_info_plus_platform_interface: ^7.0.2
  dio: ^5.7.0
  flutter_mailer: ^2.1.2
  fluttertoast: ^8.2.10
  logging: ^1.3.0
  mailer: ^6.3.0
  package_info_plus: ^8.3.0
  sentry: ^7.2.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
